language: node_js
node_js:
- '4.2'
before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
install:
- npm install -g gulp
- npm install
- jspm install
script:
- gulp bundle
- gulp deploy
env:
  global:
  - S3_BUCKET=q-s3.nzz.ch
  - KEYCDN_ZONE_ID=22499
  - KEYCDN_ZONE_URL=q-2cac.kxcdn.com
